### ISSUE TITLE
Error:Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by Hiram-Y** [iReaderAndroid/ZeusPlugin#1]
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/hiram/Library/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 2
> 编译就出现这个问题了

**Comment by jimor1234567** [comment]
请把你的编译的appt更换成aapt目录下的aapt（windows版）.exe即可。

**Comment by JamesLiAndroid** [comment]
更换过后出现了这个问题：

Execution failed for task ':ZeusPlugin:processReleaseResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/lsy-android/AndroidDev/android-sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 127

我用的是Linux系统，debian8

**Comment by jimor1234567** [comment]
你得用aapt(linux 64位版)这个文件来替换原来的aapt文件。

**Comment by JamesLiAndroid** [comment]
@jimor1234567  我对原来的aapt进行备份以后，就是用这个文件替换原来的aapt的啊

**Comment by jimor1234567** [comment]
是不是没有执行权限？linux可执行文件的结尾应该是bin后缀。详细你可以加群看一下什么错误。
